Fix #1336 (#18)
* beginning to add new location box, but not showing up

* got the search box to show up

* the popup code now works

* updated placeholder

* updated navigation code

* fixed info dialog

* modified methods to make it work

* added a quick test and the proper comparisons

* replaced functionality

* added some fix code

* updated assemblage

* fixes #1371

* fixed filters

* expliciting fixing the string

* updated

* updated

* #1371 fixes

* attempting to reveret

* fixed

* fixed phone home request

* updated s3

* for some reason the bucket is west coast

* updated s3 bucket location

* refactored exon detail panels

* updated alert

* fixed some minor refactoring

* it is doing the update properly now, without losing details

* Update https

Update https

* had forgotten a break statement

* udpated

* Update ChangeLog.md

* updated master

* was starting at the wrong coordinate site

* updated master

* was starting at the wrong coordinate site

* updated migration doc

* updated changelog

* PR that fixes #1381 (#1382)

* Fix bug in handling sequence alterations while exporting genomic sequence of features

* Add an integration test

* Fix bug where subjectStart and subjectEnd was incorrectly being incremented by 1; BLAT returns tab delimited results with 1-based coordinates (#1383)

* bumped version for release

* updated readme to 2.0.5 badge

* fixed some minor bugs

* removed unused

* selection / navigation works

* fixed some small bugs

* fixed goto function

* final fix for #1336 and removed debugging

diff --git a/apollo b/apollo
--- a/apollo
+++ b/apollo
@@ -17,6 +17,7 @@ function usage(){
     echo "test:             Runs test-suite.";
     echo "debug:            Runs from current directory in debug mode (non-minimized javascript).";
     echo "watchman:         Creates watchman daemon to autocopy plugin files (non-minimized javascript).";
+    echo "watch-jbrowse:    Creates watchman daemon to autocopy jbrowse files (non-minimized javascript).";
     echo "compile:          Compiled the build.";
     echo "clean:            Removes class files.";
     echo "clean-all:        Removes class files and jbrowse files.";
@@ -181,6 +182,12 @@ elif [[ $1 == "watchman" ]]; then
         echo "Watchman not found. Install watchman to automatically update the client side plugins for apollo development modes"
     fi
     if [ -x "$watchman_executable" ]; then $watchman_executable -- trigger $(PWD) jsfilescopy 'client/apollo/**/*.js' -- scripts/copy_client.sh; fi;
+elif [[ $1 == "watch-jbrowse" ]]; then
+    watchman_executable=$(which watchman)
+    if ! [ -x "$watchman_executable" ] ; then
+        echo "Watchman not found. Install watchman to automatically update the client side plugins for apollo development modes"
+    fi
+    if [ -x "$watchman_executable" ]; then $watchman_executable -- trigger $(PWD) jsfilescopy 'client/apollo/**/*.js' -- scripts/copy_client.sh -- ant copy-resources-dev; fi;
 elif [[ $1 == "run-app" ]];then
     check_configs
     if [[ $# == 2 ]]; then
