Fix identation

diff --git a/apollo b/apollo
--- a/apollo
+++ b/apollo
@@ -75,13 +75,13 @@ function check_configs(){
     git_executable=$(which git)
 
     if ! [ -x "$grails_executable" ] ; then
-	   if [ -f 'grailsw' ]; then 
-		   echo "Grails not found using grailsw";
-		   grails_executable="./grailsw"
-	   else
-		   echo "You must install 'grails' to install Apollo."
-		   exit 1 ;
-		fi 
+        if [ -f 'grailsw' ]; then
+            echo "Grails not found using grailsw";
+            grails_executable="./grailsw"
+        else
+           echo "You must install 'grails' to install Apollo."
+           exit 1 ;
+        fi
     fi
     if ! [ -x "$git_executable" ] ; then
        echo "You must install 'git' to install Apollo."
@@ -91,7 +91,7 @@ function check_configs(){
 }
 
 function copy_configs(){
-	rm -f src/java/apollo-config.groovy
+    rm -f src/java/apollo-config.groovy
     cp apollo-config.groovy src/java/apollo-config.groovy
 }
 
@@ -114,7 +114,7 @@ elif [[ $1 == "debug" ]];then
     # TODO: feel like there is a better way to do this
     OLD_MAVEN_OPTS=$MAVEN_OPTS
     check_configs
-	copy_configs
+    copy_configs
     export MAVEN_OPTS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
     ant devmode &
     $grails_executable -reloading debug
@@ -123,12 +123,12 @@ elif [[ $1 == "debug" ]];then
 elif [[ $1 == "test" ]];then
     # should call the copy target first
     check_configs
-	copy_configs
+    copy_configs
     $grails_executable test-app
 elif [[ $1 == "test-unit" ]];then
     # should call the copy target first
     check_configs
-	copy_configs
+    copy_configs
     $grails_executable test-app :unit
 #    mvn test
 elif [[ $1 == "deploy" ]];then
@@ -153,7 +153,7 @@ elif [[ $1 == "compile" ]];then
 elif [[ $1 == "create-rest-doc" ]];then
     check_configs
     # should call the copy target first
-	# need to copy it 
+    # need to copy it
     $grails_executable rest-api-doc && cp restapidoc.json web-app/js/restapidoc/
 elif [[ $1 == "clean-all" ]];then
     # should call the copy target first
